spring.application.name=employee-crud-with-spring-data-jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/pgdb_test
spring.datasource.username=XXXX
spring.datasource.password=XXXX
spring.datasource.hikari.schema=training
logging.level.root=info